### ISSUE TITLE
Issue with duplicate service names

### ISSUE THREAD

**Issue by injcristianrojas** [lizell/php-nagios-json#1]
Hi,

The script is very useful, but, when I have services in separate hosts with the same service name, I see only one the last in the resulting JSON. For instance, if I have a service called `service1` in `host1` and a `service1` in `host2` the script returns only the second `service1`.

Wouldn't it be better if the service keys on the JSON were composed of the host name and service description?

Thanks in advanced.

**Comment by lizell** [comment]
Of course!

Thanks for pointing that out. But what would you prefer? Having the services prefixed with the host name or add the host name as an extra level before the services, e.g:

``` javascript
"services": {
  "host1": {
    "service1": {}
  },
  "host2": {
    "service1": {}
  }
}
```

**Comment by injcristianrojas** [comment]
I like the second solution better. The first one raises one question immediately: "What separator could we use for the prefix?"

**Comment by lizell** [comment]
Exactly! ;)

**Comment by lizell** [comment]
Thanks @injcristianrojas. It is now implemented as discussed.
