### ISSUE TITLE
Data list is empty

### ISSUE THREAD

**Issue by injcristianrojas** [lizell/php-nagios-json#2]
Version c8f6318e71239fba9f6ef80bada231931e41396a of the script now renders an empty version of the statuses. See attached screenshot.

![screenshot from 2013-06-27 10 13 45](https://f.cloud.github.com/assets/862690/716346/ea6d7ebe-df33-11e2-99d3-8242115391ac.png)

**Comment by RaymiiOrg** [comment]
I have this issue as well, however, I'm using Nagios 4.

**Comment by lizell** [comment]
I'm not able to reproduce this. Can either of you provide me with a status.dat I could try with?

**Comment by RaymiiOrg** [comment]
I might have found a solution to my issue. Changing

```
$nag_version = getFileVersion($statusFile); // returns integer 2 or 3
```

to:

```
$nag_version = 3; // returns integer 2 or 3
```

My status.dat has version 4:

```
head -n 30 /usr/local/nagios/var/status.dat
########################################
#          NAGIOS STATUS FILE
#
# THIS FILE IS AUTOMATICALLY GENERATED
# BY NAGIOS.  DO NOT MODIFY THIS FILE!
########################################

info {
    created=1397713101
    version=4.0.4
    last_update_check=1397710192
    update_available=1
    last_version=4.0.4
    new_version=4.0.5
    }
```

**Comment by RaymiiOrg** [comment]
However, with version 3 manually set it does work, returns a full data set instead of an empty one...

**Comment by lizell** [comment]
Great @RaymiiOrg! Thanks for the feedback and testing this. I have now made a new version in the pull request above, #3. Could you try it out?

**Comment by RaymiiOrg** [comment]
@lizell It works on my Nagios 4 data file :+1:

**Comment by lizell** [comment]
Great! Thanks for testing it!

**Comment by RaymiiOrg** [comment]
Thank you for fixing it :hamburger:
