### ISSUE TITLE
Adding hostcomment and servicecomment

### ISSUE THREAD

**Issue by poblabs** [lizell/php-nagios-json#4]
I'm looking to see if it's possible to add `hostcomment` and `servicecomment` to the PHP JSON file? 

I've been tinkering on this for a few hours now, and keep hitting my head against the wall.

I'm hopeful you have an easy solution

**Comment by poblabs** [comment]
Seems I've tinkered long enough and have both showing in a validated JSON output.

**Comment by lizell** [comment]
Nice, would you like to contribute your code in a PR?

**Comment by poblabs** [comment]
I've never done one before - hopefully I did it right :smile:
